name: List my profile
description: Add your name to the list of most qulified dev influencers in the world
title: "<Your Name>"
labels: ["profile"]
body:
  - type: input
    attributes:
      label: What is your name?
      description: Please enter your full name
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What is your niche?
      description: Please select your niche
      multiple: true
      options:
        - Open Source
        - DevOps
        - Frontend
        - Backend
        - Fullstack
        - Mobile
        - Data Science
        - Machine Learning
        - AI
        - Blockchain
        - Security
        - Cloud
        - DevRel
        - Developer Marketing
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: socials
    attributes:
      label: Please add your socials and portfolio
      description: Please add your socials and portfolio
      value: |
        - Twitter:https://twitter.com/zevireinitz
        - GitHub: 
        - LinkedIn:
        - Portfolio:
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        If you have any questions, please contact @zevireinitz