name: Add your name to the list
description: Add your name to the list of trusted Dev Influencers open to collaborations
title: "Please add me to the list! - Raghul M"
labels: ["profile"]
body:
  - type: input
    attributes:
      label: What is your name?
      description: Please enter your full name
    validations:
      required: true
    value: "Raghul M"
  - type: dropdown
    attributes:
      label: What is the focus of your content?
      description: Please select up to 4 areas of expertise
      multiple: true
      options:
        - Open Source
        - Dev Tools
        - DevOps
        - AI/ML
        - Kubernetes
        - Docker
        - Cybersecurity
        - Webassembly
        - Dev Marketing
        - Other
      default: 0
    validations:
      required: 
    value: 
    - "Open Source"
    - "DevOps"
    - "AI/ML"
    - "Other"

    
  - type: dropdown
    attributes:
      label: What type of content do you produce?
      description: Please select the most relevant content types
      multiple: true
      options:
        - Video
        - Podcast
        - Blogs/articles
        - Newsletter
        - Social activity
        - Other
      default: 0
    validations:
      required: true
    value: 
    - "Blogs/articles"

  - type: input
    id: github
    attributes:
      label: Your Github profile link
      description: Please add the link to your GitHub profile
      value: |
        GitHub: https://github.com/Raghul-M
  - type: textarea
    id: socials
    attributes:
      label: Your social links
      description: Please add your 3 most active social links
      value: |
        YouTube: https://youtu.be/Ey-4qenjyTs?si=onOPpjdXhiS1Daxn
        Twitter: https://twitter.com/RaghulM01
        LinkedIn: https://www.linkedin.com/in/m-raghul/
        Dev.to: https://dev.to/raghul
        Anything else...:
    validations:
      required: false
  - type: input
    id: audience
    attributes:
      label: Your total audience size
      description: How many subscribers/followers do you have across all platforms? Please send one number.
      value: |
        Total followers: 1.2k
    validations:
      required: false
  - type: input
    id: portfolio
    attributes:
      label: Your portfolio site
      description: Please add a link to your portfolio so people can review and easily contact you
      value: |
        Portfolio: https://raghul-m.github.io/
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        
        We review each application and include as many applicants as possible, but we can't make any blanket guarantees. If you have any questions, please contact us at [influencerdotdev@gmail.com](mailto:influencerdotdev@gmail.com)

        Please also subscribe to the exclusive [influencer.dev mailing list](https://forms.gle/jFK8Xj6WMjb7ZMb69) to receive job/project opportunities that we've recived from companies in the industry. It's an easy way to find collaboration opportunities that fit your expertise and skill set.
        