name: Add your name to the list
description: Add your name to the list of trusted Dev Influencers open to collaborations
title: "Please add me to the list! - <your name>"
labels: ["profile"]
body:
  - type: input
    attributes:
      label: What is your  name?
      description: Please enter your full name
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What is the focus of your content?
      description: Please select up to 4 areas of expertise
      multiple: true
      options:
        - Open Source
        - Dev Tools
        - DevOps
        - AI/ML
        - Kubernetes
        - Docker
        - Cybersecurity
        - Dev Marketing
        - Other
      default: 0
    validations:
      required: true
      
   - type: input
    id: github
    attributes:
      label: Your Github profile link
      description: Please add the link to your GitHub profile
      # value: https://github.com/zevireinitz
      
  - type: textarea
    id: socials
    attributes:
      label: Your social links
      description: Please add your 3 most active social links
      value: |
        - YouTube: https://www.youtube.com/@getlivecycle
        - Twitter: https://twitter.com/zevireinitz
        - LinkedIn: https://www.linkedin.com/in/zevi
        -
    validations:
      required: false
      
  # - type: input
  #   id: audience
  #   attributes:
  #     label: Your total audience size
  #     description: How many subscribers/followers do you have across all platforms? Please send one number.
  #     value: Total followers: 100K
  #   validations:
  #     required: false
      
  # - type: input
  #   id: portfolio
  #   attributes:
  #     label: Your portfolio site
  #     description: Please add a link to your portfolio so people can review and easily contact you
  #     value: Portfolio: https://zevi.super.site
  #   validations:
  #     required: false

  # - type: markdown
  #   attributes:
  #     value: |
  #       We review each application and include as many applicants as possible, but we can't make any blanket guarantees. If you have any questions, please contact us at [influencerdotdev@gmail.com](mailto:influencerdotdev@gmail.com)
